openapi: 3.1.0
info:
  title: hackathon_22_winter_01
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
paths:
  /ping:
    get:
      summary: GET /ping
      tags:
        - ping
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
      operationId: ping
      description: ヘルスチェック用のエンドポイント
  /ws:
    get:
      summary: GET /ws
      tags:
        - ws
      parameters:
        - name: playerId
          schema:
            $ref: '#/components/schemas/PlayerId'
          in: query
          required: true
          description: ユーザーUUID
      responses:
        '200':
          description: OK
      operationId: connect-to-ws
      description: |-
        Websocketを用いて双方向通信を行う
        - クライアント → サーバー (送信)
          - `#/components/schemas/WsRequest`型のJSON文字列をサーバーに送信します
          - `type`が`XXX`のとき`body`の型は`#/components/schemas/WsRequestBodyXXX`です
        - サーバー → クライアント (受信)
          - `#/components/schemas/WsResponse`型のJSON文字列をサーバーに送信します
          - `type`が`XXX`のとき`body`の型は`#/components/schemas/WsResponseBodyXXX`です
components:
  schemas:
    PlayerId:
      title: PlayerId
      type: string
      format: uuid
      description: プレイヤーUUID
    CardId:
      title: CardId
      type: string
      format: uuid
      description: カードUUID
    RailId:
      title: RailId
      type: string
      format: uuid
      description: レールUUID
    CardType:
      title: CardType
      type: string
      enum:
        - yolo
        - galaxyBrain
        - openSourcerer
        - refactoring
        - pairExtraordinaire
        - lgtm
        - pullShark
        - starstruck
        - zeroDay
        - ooops
        - none
      description: カードの効果の種類
    LifeEventType:
      title: LifeEventType
      type: string
      enum:
        - damaged
        - healed
      description: ライフに関するイベントの種類
    BlockEventType:
      title: BlockEventType
      type: string
      enum:
        - canceled
        - crashed
      description: ブロックに関するイベントの種類
    Card:
      title: Card
      type: object
      properties:
        id:
          $ref: '#/components/schemas/CardId'
        type:
          $ref: '#/components/schemas/CardType'
      required:
        - id
        - type
      description: カード情報
    Player:
      title: Player
      type: object
      properties:
        id:
          $ref: '#/components/schemas/PlayerId'
          description: プレイヤーのレールのリスト
        name:
          type: string
          description: プレイヤーの名前
        life:
          $ref: '#/components/schemas/Life'
      required:
        - id
        - name
        - life
      description: プレイヤー情報
    RailIndex:
      title: RailIndex
      type: integer
      minimum: 0
      maximum: 6
      description: レールのインデックス
    Life:
      title: Life
      type: number
      maximum: 100
      minimum: 0
      description: ライフ
    WsRequest:
      title: WsRequest
      type: object
      properties:
        type:
          $ref: '#/components/schemas/WsRequestType'
        body:
          oneOf:
            - $ref: '#/components/schemas/WsRequestBodyGameStartEvent'
            - $ref: '#/components/schemas/WsRequestBodyLifeEvent'
            - $ref: '#/components/schemas/WsRequestBodyCardEvent'
            - $ref: '#/components/schemas/WsRequestBodyBlockEvent'
            - $ref: '#/components/schemas/WsRequestBodyCardForAllEvent'
          description: イベントの情報
      required:
        - type
        - body
      description: Websocket接続中にサーバーに送信するオブジェクト
    WsRequestType:
      title: WsRequestType
      type: string
      enum:
        - gameStartEvent
        - lifeEvent
        - cardEvent
        - blockEvent
        - cardForAllEvent
      description: イベントの種類
    WsRequestBodyGameStartEvent:
      title: WsRequestBodyGameStartEvent
      type: object
      description: ゲーム開始時にサーバーに送信するオブジェクト
    WsRequestBodyLifeEvent:
      title: WsRequestBodyLifeEvent
      type: object
      properties:
        type:
          $ref: '#/components/schemas/LifeEventType'
        diff:
          type: number
          description: ライフの変化量
      required:
        - type
        - diff
      description: ライフに関するイベントの情報
    WsRequestBodyCardEvent:
      title: WsRequestBodyCardEvent
      type: object
      properties:
        id:
          $ref: '#/components/schemas/CardId'
        targetId:
          $ref: '#/components/schemas/PlayerId'
        type:
          $ref: '#/components/schemas/CardType'
      required:
        - id
        - targetId
        - type
      description: カードに関するイベントの情報
    WsRequestBodyBlockEvent:
      title: WsRequestBodyBlockEvent
      type: object
      properties:
        type:
          $ref: '#/components/schemas/BlockEventType'
        cardType:
          $ref: '#/components/schemas/CardType'
        railIndex:
          $ref: '#/components/schemas/RailIndex'
      required:
        - type
        - railIndex
      description: ブロックに関するイベントの情報
    WsRequestBodyCardForAllEvent:
      title: WsRequestBodyCardForAllEvent
      type: object
      properties:
        id:
          $ref: '#/components/schemas/CardId'
        type:
          $ref: '#/components/schemas/CardType'
      required:
        - id
        - type
      description: 全プレイヤーに影響を与えるカードに関するイベントの情報
    WsResponse:
      title: WsResponse
      type: object
      properties:
        type:
          $ref: '#/components/schemas/WsResponseType'
        body:
          oneOf:
            - $ref: '#/components/schemas/WsResponseBodyConnected'
            - $ref: '#/components/schemas/WsResponseBodyGameStarted'
            - $ref: '#/components/schemas/WsResponseBodyLifeChanged'
            - $ref: '#/components/schemas/WsResponseBodyRailCreated'
            - $ref: '#/components/schemas/WsResponseBodyRailMerged'
            - $ref: '#/components/schemas/WsResponseBodyBlockCreated'
            - $ref: '#/components/schemas/WsResponseBodyBlockCanceled'
            - $ref: '#/components/schemas/WsResponseBodyBlockCrashed'
            - $ref: '#/components/schemas/WsResponseBodyGameOverred'
          description: イベントの情報
        eventTime:
          type: string
          format: date-time
          description: イベントの発生時刻
      required:
        - type
        - body
        - eventTime
      description: Websocket接続中にサーバーから受信するオブジェクト
    WsResponseType:
      title: WsResponseType
      type: string
      enum:
        - connected
        - gameStarted
        - lifeChanged
        - railCreated
        - railMerged
        - blockCreated
        - blockCanceled
        - blockCrashed
        - gameOverred
        - noop
      description: イベントの種類
    WsResponseBodyConnected:
      type: object
      properties:
        playerId:
          $ref: '#/components/schemas/PlayerId'
      required:
        - playerId
      description: 接続したプレイヤーのID
    WsResponseBodyGameStarted:
      type: object
      properties:
        players:
          type: array
          items:
            $ref: '#/components/schemas/Player'
          description: 各プレイヤーの情報
      required:
        - players
      description: ゲーム開始時の情報
    WsResponseBodyLifeChanged:
      type: object
      properties:
        playerId:
          $ref: '#/components/schemas/PlayerId'
        cardType:
          $ref: '#/components/schemas/CardType'
        newLife:
          $ref: '#/components/schemas/Life'
          description: 変動後のライフ
      required:
        - playerId
        - newLife
      description: ライフの変動情報
    WsResponseBodyRailCreated:
      type: object
      properties:
        newRail:
          $ref: '#/components/schemas/RailIndex'
          description: 新規に作成されたレールのインデックス
        parentRail:
          $ref: '#/components/schemas/RailIndex'
          description: 分岐元のレールのインデックス
        attackerId:
          $ref: '#/components/schemas/PlayerId'
        targetId:
          $ref: '#/components/schemas/PlayerId'
        cardType:
          $ref: '#/components/schemas/CardType'
      required:
        - newRail
        - parentRail
        - attackerId
        - targetId
        - cardType
      description: 新規レールの作成情報
    WsResponseBodyRailMerged:
      type: object
      properties:
        childRail:
          $ref: '#/components/schemas/RailIndex'
          description: マージされたレールのインデックス
        parentRail:
          $ref: '#/components/schemas/RailIndex'
          description: 結合先のレールのインデックス
        playerId:
          $ref: '#/components/schemas/PlayerId'
        cardType:
          $ref: '#/components/schemas/CardType'
      required:
        - childRail
        - parentRail
        - playerId
        - cardType
      description: レールのマージ情報
    WsResponseBodyBlockCreated:
      type: object
      properties:
        attackerId:
          $ref: '#/components/schemas/PlayerId'
        targetId:
          $ref: '#/components/schemas/PlayerId'
        cardType:
          $ref: '#/components/schemas/CardType'
        railIndex:
          $ref: '#/components/schemas/RailIndex'
        delay:
          type: integer
          minimum: 1
          maximum: 5
          description: 障害物を解消するために必要な秒数
        attack:
          type: number
          format: float
          minimum: 10
          maximum: 50
          description: 障害物と衝突したときに与えるダメージ
      required:
        - attackerId
        - targetId
        - cardType
        - railIndex
        - delay
        - attack
      description: 新規障害物の作成情報
    WsResponseBodyBlockCanceled:
      type: object
      properties:
        targetId:
          $ref: '#/components/schemas/PlayerId'
        railIndex:
          $ref: '#/components/schemas/RailIndex'
        cardType:
          $ref: '#/components/schemas/CardType'
      required:
        - targetId
        - railIndex
      description: 障害物の解消情報
    WsResponseBodyBlockCrashed:
      type: object
      properties:
        targetId:
          $ref: '#/components/schemas/PlayerId'
        railIndex:
          $ref: '#/components/schemas/RailIndex'
          description: 衝突したレールのインデックス
        cardType:
          $ref: '#/components/schemas/CardType'
      required:
        - targetId
        - railIndex
      description: 障害物と衝突したときの情報
    WsResponseBodyGameOverred:
      type: object
      properties:
        playerId:
          $ref: '#/components/schemas/PlayerId'
      required:
        - playerId
tags:
  - name: ping
    description: Ping API
  - name: ws
    description: Websocket API
