// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package oapi

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GET /ws
	// (GET /ws)
	GetWs(ctx echo.Context) error
	// oapi-codegenのための仮エンドポイント (使用できません)
	// (GET /ws-schemas)
	GetWsSchemas(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetWs converts echo context to params.
func (w *ServerInterfaceWrapper) GetWs(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetWs(ctx)
	return err
}

// GetWsSchemas converts echo context to params.
func (w *ServerInterfaceWrapper) GetWsSchemas(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetWsSchemas(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/ws", wrapper.GetWs)
	router.GET(baseURL+"/ws-schemas", wrapper.GetWsSchemas)

}

type GetWsRequestObject struct {
}

type GetWsResponseObject interface {
	VisitGetWsResponse(w http.ResponseWriter) error
}

type GetWs200Response struct {
}

func (response GetWs200Response) VisitGetWsResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type GetWsSchemasRequestObject struct {
	Body *GetWsSchemasJSONRequestBody
}

type GetWsSchemasResponseObject interface {
	VisitGetWsSchemasResponse(w http.ResponseWriter) error
}

type GetWsSchemas200JSONResponse WsResponse

func (response GetWsSchemas200JSONResponse) VisitGetWsSchemasResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GET /ws
	// (GET /ws)
	GetWs(ctx context.Context, request GetWsRequestObject) (GetWsResponseObject, error)
	// oapi-codegenのための仮エンドポイント (使用できません)
	// (GET /ws-schemas)
	GetWsSchemas(ctx context.Context, request GetWsSchemasRequestObject) (GetWsSchemasResponseObject, error)
}

type StrictHandlerFunc func(ctx echo.Context, args interface{}) (interface{}, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetWs operation middleware
func (sh *strictHandler) GetWs(ctx echo.Context) error {
	var request GetWsRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetWs(ctx.Request().Context(), request.(GetWsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWs")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetWsResponseObject); ok {
		return validResponse.VisitGetWsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}

// GetWsSchemas operation middleware
func (sh *strictHandler) GetWsSchemas(ctx echo.Context) error {
	var request GetWsSchemasRequestObject

	var body GetWsSchemasJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetWsSchemas(ctx.Request().Context(), request.(GetWsSchemasRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWsSchemas")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetWsSchemasResponseObject); ok {
		return validResponse.VisitGetWsSchemasResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("Unexpected response type: %T", response)
	}
	return nil
}
