## gitea に同期する用の actions
name: push-to-gitea

on:
  push:
    branches:
      - 'main'

env:
  GITEA_SSH_URL: 'ssh://git@git.trap.jp:2200/hackathon-22-winter-01/back-end.git'

jobs:
  sync:
    name: sync
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set config
        run: |
          echo "${{ secrets.GITEA_TOKEN }}" > ~/deploy_key.pem
          chmod 600 ~/deploy_key.pem
          git config --local user.email "github@actions"
          git config --local user.name "github"
      - name: Push changes
        env:
          GIT_SSH_COMMAND: ssh -i ~/deploy_key.pem -o StrictHostKeyChecking=no -F /dev/null
        run: |
          git fetch --unshallow origin
          git push -f ${{ env.GITEA_SSH_URL }} main:master
